name = "minghinshi's Adventure"
author = "minghinshi"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "beae03bdc4ea5145b6ee376928cae0372cb54c9be213f554db516784453ec50d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
