#Common Settings
[common]
	#Disable / enable any items here (disables their recipes)
	enabledItems = ["sophisticatedbackpacks:void_upgrade|true",
	"sophisticatedbackpacks:advanced_refill_upgrade|true",
	"sophisticatedbackpacks:copper_backpack|true",
	"sophisticatedbackpacks:crafting_upgrade|false",
	"sophisticatedbackpacks:advanced_pump_upgrade|false",
	"sophisticatedbackpacks:upgrade_base|true",
	"sophisticatedbackpacks:alchemy_upgrade|false",
	"sophisticatedbackpacks:filter_upgrade|false",
	"sophisticatedbackpacks:advanced_deposit_upgrade|true",
	"sophisticatedbackpacks:smithing_upgrade|false",
	"sophisticatedbackpacks:magnet_upgrade|false",
	"sophisticatedbackpacks:anvil_upgrade|false",
	"sophisticatedbackpacks:advanced_pickup_upgrade|true",
	"sophisticatedbackpacks:jukebox_upgrade|false",
	"sophisticatedbackpacks:xp_pump_upgrade|false",
	"sophisticatedbackpacks:tank_upgrade|false",
	"sophisticatedbackpacks:iron_backpack|true",
	"sophisticatedbackpacks:auto_smelting_upgrade|false",
	"sophisticatedbackpacks:advanced_void_upgrade|true",
	"sophisticatedbackpacks:pickup_upgrade|true",
	"sophisticatedbackpacks:auto_smoking_upgrade|false",
	"sophisticatedbackpacks:smoking_upgrade|false",
	"sophisticatedbackpacks:everlasting_upgrade|false",
	"sophisticatedbackpacks:stack_upgrade_tier_4|false",
	"sophisticatedbackpacks:stack_upgrade_tier_2|false",
	"sophisticatedbackpacks:stack_upgrade_tier_3|false",
	"sophisticatedbackpacks:stack_upgrade_tier_1|false",
	"sophisticatedbackpacks:restock_upgrade|true",
	"sophisticatedbackpacks:compacting_upgrade|false",
	"sophisticatedbackpacks:stack_downgrade_tier_2|false",
	"sophisticatedbackpacks:stack_downgrade_tier_1|false",
	"sophisticatedbackpacks:stack_downgrade_tier_3|false",
	"sophisticatedbackpacks:advanced_restock_upgrade|true",
	"sophisticatedbackpacks:stack_upgrade_omega_tier|false",
	"sophisticatedbackpacks:advanced_magnet_upgrade|false",
	"sophisticatedbackpacks:stonecutter_upgrade|false",
	"sophisticatedbackpacks:advanced_compacting_upgrade|false",
	"sophisticatedbackpacks:advanced_jukebox_upgrade|false",
	"sophisticatedbackpacks:stack_upgrade_starter_tier|false",
	"sophisticatedbackpacks:blasting_upgrade|false",
	"sophisticatedbackpacks:refill_upgrade|true",
	"sophisticatedbackpacks:backpack|true",
	"sophisticatedbackpacks:auto_blasting_upgrade|false",
	"sophisticatedbackpacks:pump_upgrade|false",
	"sophisticatedbackpacks:deposit_upgrade|true",
	"sophisticatedbackpacks:advanced_tool_swapper_upgrade|false",
	"sophisticatedbackpacks:tool_swapper_upgrade|false",
	"sophisticatedbackpacks:advanced_filter_upgrade|false",
	"sophisticatedbackpacks:advanced_alchemy_upgrade|false",
	"sophisticatedbackpacks:smelting_upgrade|false",
	"sophisticatedbackpacks:feeding_upgrade|false",
	"sophisticatedbackpacks:battery_upgrade|false",
	"sophisticatedbackpacks:advanced_feeding_upgrade|false",
	"sophisticatedbackpacks:diamond_backpack|true",
	"sophisticatedbackpacks:gold_backpack|true",
	"sophisticatedbackpacks:inception_upgrade|false",
	"sophisticatedbackpacks:netherite_backpack|true",
	"sophisticatedbackpacks:infinity_upgrade|false",
	"sophisticatedbackpacks:survival_infinity_upgrade|false"]
